import { Lato } from 'next/font/google';
import './globals.css';

const inter = Lato({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata = {
    title: 'Gaus Al Munir Tushar | Software Engineer',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="scroll-smooth bg-secondary">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
